@startuml

participant ":VaccinationCenterStatsRecorderRecurringTask" as User #A9DCDF


title SSD: Generating for each vaccination center a daily report

activate "User" #F0FFFF
"User" -> ":System":Schedule task to generate a daily report
activate ":System" 	#E6E6FA


deactivate "User"

'*https://www.w3.org/TR/css-color-4/#hex-notation*'

@enduml

