@startuml US04_SSD
autonumber
actor "Receptionist" as Recp

activate Recp
Recp -> ":System" : starts registering the arrivel of SNS User
activate ":System"
":System" --> Recp : requests to select the vaccination center
deactivate ":System"

Recp -> ":System" : select the vaccination center
activate ":System"
":System" --> Recp : request data (snsUserNumber, arrivalTime)
deactivate ":System"

Recp -> ":System" : types requested data
activate ":System"
":System" --> Recp : shows the SNS User has an Vaccine Schedule s and requests a confirmation
deactivate ":System"

Recp -> ":System" : confirms the data
activate ":System"
":System" --> Recp : informs operation success
deactivate ":System"

deactivate Recp

@enduml